# Jekyll configuration for hf-general-ci-tools documentation
title: "hf-general-ci-tools"
description: "A collection of reusable GitHub Actions workflows for general CI/CD tasks"
baseurl: "/hf-general-ci-tools"  # GitHub Pages subpath
url: "https://n3b3x.github.io"

# Theme and plugins
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge

# Site settings
timezone: UTC
encoding: utf-8

# Just the Docs configuration
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true

# Navigation
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/n3b3x/hf-general-ci-tools
  - title: Issues
    url: https://github.com/n3b3x/hf-general-ci-tools/issues

# Just the Docs specific settings
aux_links:
  GitHub Repository:
    - https://github.com/n3b3x/hf-general-ci-tools
  Issues:
    - https://github.com/n3b3x/hf-general-ci-tools/issues

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE

# Include files that are normally excluded
include:
  - _pages

# Just the Docs theme settings
color_scheme: light

# SEO settings
seo:
  type: "Organization"
  name: "hf-general-ci-tools"
  description: "Reusable GitHub Actions workflows for CI/CD"
  url: "https://n3b3x.github.io/hf-general-ci-tools"
  image: "/assets/logo.png"
