# Jekyll configuration for hf-general-ci-tools documentation
title: "hf-general-ci-tools"
description: "A comprehensive collection of reusable GitHub Actions workflows for general CI/CD tasks, including C/C++ linting, static analysis, documentation generation, and link checking"
baseurl: "/hf-general-ci-tools"  # GitHub Pages subpath
url: "https://n3b3x.github.io"

# Jekyll source configuration - tells Jekyll to use docs folder as source
source: docs

# Author and social information
author:
  name: "N3b3x"
  email: "n3b3x@example.com"
  url: "https://github.com/n3b3x"

# Theme and plugins
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-optional-front-matter

# Markdown and syntax highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Site settings
timezone: UTC
encoding: utf-8
lang: en

# Just the Docs configuration
search_enabled: true
search:
  heading_level: 3
  previews: 5
  preview_words_before: 10
  preview_words_after: 15
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

# Navigation and UI enhancements
nav_enabled: true
heading_anchors: true
breadcrumbs: true
toc:
  min_level: 2
  max_level: 4

# Callouts for better content presentation
callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: yellow
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: red

# Visual enhancements
color_scheme: custom  # Custom enhanced theme

# Auxiliary links with better organization
aux_links:
  "📚 GitHub Repository":
    - "https://github.com/n3b3x/hf-general-ci-tools"
  "🐛 Report Issues":
    - "https://github.com/n3b3x/hf-general-ci-tools/issues"
  "⭐ Star on GitHub":
    - "https://github.com/n3b3x/hf-general-ci-tools/stargazers"

# External navigation links
nav_external_links:
  - title: "📚 GitHub Repository"
    url: https://github.com/n3b3x/hf-general-ci-tools
  - title: "🐛 Issues"
    url: https://github.com/n3b3x/hf-general-ci-tools/issues

# Footer customization
footer_content: "Built with ❤️ using <a href='https://just-the-docs.github.io/just-the-docs/'>Just the Docs</a> • <a href='https://github.com/n3b3x/hf-general-ci-tools/blob/main/LICENSE'>MIT License</a> • <a href='https://github.com/n3b3x/hf-general-ci-tools'>View on GitHub</a>"

# Collections for better organization
collections:
  docs:
    permalink: "/:path/"
    output: true
    sort_by: nav_order

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false
  custom_css:
    - assets/css/custom.css

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - "*.gem"
  - "*.gemspec"
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata

# Include files that are normally excluded
include:
  - _pages

# Enhanced SEO settings
seo:
  type: "Organization"
  name: "hf-general-ci-tools"
  description: "Reusable GitHub Actions workflows for CI/CD tasks including C/C++ linting, static analysis, documentation generation, and link checking"
  url: "https://n3b3x.github.io/hf-general-ci-tools"
  twitter:
    card: "summary_large_image"
    site: "@n3b3x"
  og:
    type: "website"
    locale: "en_US"

# Social media and sharing
social:
  name: "hf-general-ci-tools"
  links:
    - "https://github.com/n3b3x/hf-general-ci-tools"
    - "https://github.com/n3b3x"

# Analytics (uncomment and configure if needed)
# ga_tracking: UA-XXXXXXXXX-X
# ga_tracking_anonymize_ip: true

# Performance optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]