name: 📚 Build Documentation

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: 🏗️ Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: 📦 Install Jekyll dependencies
      run: |
        gem install jekyll bundler
        bundle install

    - name: 📝 Run Markdown Linting
      run: |
        # Install markdownlint-cli
        npm install -g markdownlint-cli
        
        # Run markdown linting on all markdown files
        markdownlint "**/*.md" --ignore node_modules --ignore .git --ignore _site

    - name: ✍️ Run Spell Check
      run: |
        # Install cspell
        npm install -g cspell
        
        # Run spell check on all markdown files
        cspell "**/*.md" --ignore-paths "node_modules,.git,_site" --config .cspell.json || true

    - name: 🔗 Check Documentation Links
      uses: lycheeverse/lychee-action@v2
      with:
        args: --verbose --no-progress --format detailed --output lychee.txt
        files: "docs/**,*.md"
        fail: true
        timeout: 10
        retry: 3
        exclude-all-private: true
        exclude-mail: true

    - name: 🏗️ Build Jekyll Site
      run: |
        # Set environment for production build
        export JEKYLL_ENV=production
        
        # Build the site
        bundle exec jekyll build --config _config.yml,_config_prod.yml --destination _site

    - name: 📊 Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jekyll-site
        path: _site/
        retention-days: 30

    - name: 🚀 Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/deploy-pages@v4
      with:
        artifact_name: jekyll-site
        environment_name: github-pages