---
# Jekyll Production Configuration
# This file contains production-specific settings that override the base configuration
# Usage: jekyll build --config _config.yml,_config_prod.yml

# Production URL settings
url: "https://n3b3x.github.io"
baseurl: "/hf-general-ci-tools"

# Production-specific optimizations
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]

# Production analytics (uncomment and configure if needed)
# ga_tracking: UA-XXXXXXXXX-X
# ga_tracking_anonymize_ip: true

# Production-specific SEO settings
seo:
  type: "Organization"
  name: "hf-general-ci-tools"
  description: >
    Reusable GitHub Actions workflows for CI/CD tasks including C/C++ linting,
    static analysis, documentation generation, and link checking
  url: "https://n3b3x.github.io/hf-general-ci-tools"
  twitter:
    card: "summary_large_image"
    site: "@n3b3x"
  og:
    type: "website"
    locale: "en_US"

# Production-specific social links
social:
  name: "hf-general-ci-tools"
  links:
    - "https://github.com/n3b3x/hf-general-ci-tools"
    - "https://github.com/n3b3x"

# Production-specific footer
footer_content: >
  Built with ❤️ using <a href='https://just-the-docs.github.io/just-the-docs/'>Just the Docs</a> •
  <a href='https://github.com/n3b3x/hf-general-ci-tools/blob/main/LICENSE'>GPL v3 License</a> •
  <a href='https://github.com/n3b3x/hf-general-ci-tools'>View on GitHub</a>

# Production-specific performance settings (CI-optimized)
incremental: false  # Disable incremental builds for production (prevents stale content)
future: false       # Don't publish future-dated posts (prevent future content publishing)
drafts: false       # Don't publish draft posts (focus on finalized content)
unpublished: false  # Don't publish unpublished posts (focus on published content)
safe: true          # Enable safe mode (more secure and predictable)
verbose: true       # Enable verbose output (better for CI debugging)
profile: false      # Disable profiling (reduces build time)
strict_front_matter: true  # Fail on front matter errors (ensure content integrity)
lsi: false          # Disable LSI (resource-intensive, not needed for CI)

# Production-specific exclude patterns
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE
  - "*.gem"
  - "*.gemspec"
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - _config.development.yml
  - _config.local.yml
  - .env
  - .env.local
  - .env.development
  - .env.production

# Production-specific include patterns
include:
  - _pages
