var searchData=
[
  ['general_20ci_20tools_0',['General ci tools',['../index.html#autotoc_md2',1,'🚀 hf-general-ci-tools'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/index.md#autotoc_md61',1,'hf-general-ci-tools']]],
  ['generated_20files_1',['Check generated files',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md396',1,'']]],
  ['generated_20files_2',['Generated Files',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md378',1,'']]],
  ['generated_20url_20format_3a_20strong_3',['&lt;strong&gt;Generated URL Format:&lt;/strong&gt;',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ru-docs-publish.md#autotoc_md291',1,'']]],
  ['generation_4',['Documentation Generation',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/index.md#autotoc_md78',1,'']]],
  ['generation_20and_20comment_20handling_5',['🔧 Configuration Generation and Comment Handling',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/jekyll-guide.md#autotoc_md103',1,'']]],
  ['generation_20failures_20strong_6',['&lt;strong&gt;Configuration Generation Failures&lt;/strong&gt;',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ru-docs-publish.md#autotoc_md315',1,'']]],
  ['generation_20strong_7',['&lt;strong&gt;Version-Specific Configuration Generation&lt;/strong&gt;',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/jekyll-guide.md#autotoc_md106',1,'']]],
  ['generation_3a_20strong_8',['&lt;strong&gt;Automatic Version Generation:&lt;/strong&gt;',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md368',1,'']]],
  ['geometry_2ec_9',['geometry.c',['../geometry_8c.html',1,'']]],
  ['geometry_2eh_10',['geometry.h',['../geometry_8h.html',1,'']]],
  ['geometry_5fhypotenuse_11',['geometry_hypotenuse',['../geometry_8h.html#a1a73f7680e6a695ebc9d7a706ceedcd4',1,'geometry_hypotenuse(double leg_a, double leg_b):&#160;geometry.c'],['../geometry_8c.html#a1a73f7680e6a695ebc9d7a706ceedcd4',1,'geometry_hypotenuse(double leg_a, double leg_b):&#160;geometry.c']]],
  ['geometry_5frectangle_5farea_12',['geometry_rectangle_area',['../geometry_8h.html#aa259decaf155eda8d3ffae3c945d1645',1,'geometry_rectangle_area(double width, double height):&#160;geometry.c'],['../geometry_8c.html#aa259decaf155eda8d3ffae3c945d1645',1,'geometry_rectangle_area(double width, double height):&#160;geometry.c']]],
  ['geometry_5frectangle_5fperimeter_13',['geometry_rectangle_perimeter',['../geometry_8h.html#a71da5aa67e4e3fa012fad162bec36cda',1,'geometry_rectangle_perimeter(double width, double height):&#160;geometry.c'],['../geometry_8c.html#a71da5aa67e4e3fa012fad162bec36cda',1,'geometry_rectangle_perimeter(double width, double height):&#160;geometry.c']]],
  ['gets_20deployed_20where_3a_20strong_14',['&lt;strong&gt;What Gets Deployed Where:&lt;/strong&gt;',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ru-docs-publish.md#autotoc_md299',1,'']]],
  ['getting_20help_15',['Getting Help',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/jekyll-guide.md#autotoc_md134',1,'Getting Help'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md398',1,'Getting Help']]],
  ['git_20authentication_20errors_20strong_16',['&lt;strong&gt;Git Authentication Errors&lt;/strong&gt;',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ru-docs-publish.md#autotoc_md317',1,'']]],
  ['git_20based_20versioning_20enforced_17',['1. Git-Based Versioning (Enforced)',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md389',1,'']]],
  ['github_20pages_20setup_18',['GitHub Pages Setup',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ru-docs-publish.md#autotoc_md303',1,'🌐 GitHub Pages Setup'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ru-docs-publish.md#autotoc_md296',1,'GitHub Pages Setup']]],
  ['greet_19',['greet',['../classci__demo_1_1Greeter.html#a1c6f59ec22d7ac944ca89d0a1f4b9714',1,'ci_demo::Greeter']]],
  ['greeter_20',['Greeter',['../classci__demo_1_1Greeter.html',1,'ci_demo::Greeter'],['../classci__demo_1_1Greeter.html#a463ccb16afc3aef09bcef35d9a3d379f',1,'ci_demo::Greeter::Greeter(std::string salutation)'],['../classci__demo_1_1Greeter.html#a1fc29f7adb946034eaf6283174967f48',1,'ci_demo::Greeter::Greeter()']]],
  ['greeter_2ecpp_21',['greeter.cpp',['../greeter_8cpp.html',1,'']]],
  ['greeter_2ehpp_22',['greeter.hpp',['../greeter_8hpp.html',1,'']]],
  ['guide_23',['Guide',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md349',1,'🔀 Documentation Versioning Guide'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/jekyll-guide.md#autotoc_md86',1,'🔧 Jekyll Configuration Guide']]],
  ['guide_20jekyll_20guide_24',['@page md_docs_2jekyll-guide jekyll-guide',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/jekyll-guide.md#autotoc_md84',1,'']]],
  ['guide_20versioning_20guide_25',['@page md_docs_2versioning-guide versioning-guide',['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md347',1,'']]],
  ['guides_26',['Guides',['../index.html#autotoc_md13',1,'📖 Available Guides'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/ci-workflows.md#autotoc_md55',1,'📚 Related Guides'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/jekyll-guide.md#autotoc_md85',1,'parent: &quot;📖 Examples &amp; Guides&quot;'],['..//home/runner/work/hf-general-ci-tools/hf-general-ci-tools/docs/versioning-guide.md#autotoc_md348',1,'parent: &quot;📖 Examples &amp; Guides&quot;']]]
];
