---
name: Documentation Link Check (Reusable)

on:
  workflow_call:
    inputs:
      paths:
        description: "Comma-separated paths to check for broken links"
        type: string
        default: "docs/**,*.md,**/docs/**"
      fail_on_errors:
        description: "Fail the workflow if broken links are found"
        type: boolean
        default: true

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check documentation links
        uses: AlexanderDokuchaev/md-dead-link-check@v1.2.0
